### ISSUE TITLE
Typo or impl error, about `mod` or `rem`

### ISSUE THREAD

**Issue by A4-Tacks** [zzjrabbit/caraint#6]
```rust
use dashu_int::IBig;

fn main() {
    let n = IBig::from(-8);
    assert_eq!(&n % 3, -2); // Rem (remainder)
    assert_ne!(&n % 3, 1); // Mod (modulus)
}
```

https://github.com/zzjrabbit/caraint/blob/2b34eb3bf93a66443e0df2df2020ac76def2f7a4/src/backend/mod.rs#L243

`Op::Mod` implemented `Rem` operation

**Comment by wenxuanjun** [comment]
It appears to be as expected.

In original design the `%` only represents the `%` operator and is not tied to specific semantics like `Rem` or `Mod`.

I intend to delegate the operation of number entirely to dashu crate, depending on the exact behavior of dashu.

**Comment by A4-Tacks** [comment]
> In original design the `%` only represents the `%` operator and is not tied to specific semantics like `Rem` or `Mod`.
> 
> I intend to delegate the operation of number entirely to dashu crate, depending on the exact behavior of dashu.

`%` The name is `core::ops::Rem`

**Comment by wenxuanjun** [comment]
> `%` The name is `core::ops::Rem``%`

You're right, I made a conceptual mistake. The concept of `%` specified in Rust is `Rem`, not others. Will fix this error in the next commit and thanks for your issue.
